import { type VideoStatus } from "./api";
import { useVideos } from "./useVideos";
import { VideoCard } from "./VideoCard";

const STATUS_ORDER: VideoStatus[] = [
  "pending_review",
  "generating",
  "approved",
  "publishing",
  "published",
  "rejected",
  "failed",
];

const STATUS_LABELS: Record<VideoStatus, string> = {
  pending_review: "Pending Review",
  generating: "Generating",
  approved: "Approved",
  publishing: "Publishing",
  published: "Published",
  rejected: "Rejected",
  failed: "Failed",
};

export function VideosPage() {
  const { data: videos, isLoading, isError } = useVideos();

  if (isLoading) {
    return (
      <div className="space-y-2">
        {[1, 2, 3].map((i) => (
          <div key={i} className="h-24 animate-pulse rounded-lg bg-slate-100" />
        ))}
      </div>
    );
  }

  if (isError) {
    return (
      <p className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-600">
        Failed to load videos.
      </p>
    );
  }

  if (!videos || videos.length === 0) {
    return (
      <section className="rounded-lg border border-dashed border-slate-300 bg-white p-10 text-center">
        <h2 className="text-xl font-semibold">No videos yet</h2>
        <p className="mt-2 text-slate-500">
          Videos generated by the pipeline will appear here.
        </p>
      </section>
    );
  }

  const grouped = Object.fromEntries(
    STATUS_ORDER.map((s) => [s, videos.filter((v) => v.status === s)]),
  ) as Record<VideoStatus, typeof videos>;

  return (
    <div className="space-y-8">
      {STATUS_ORDER.filter((s) => grouped[s].length > 0).map((status) => (
        <section key={status}>
          <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-500">
            {STATUS_LABELS[status]}{" "}
            <span className="font-normal text-slate-400">
              ({grouped[status].length})
            </span>
          </h2>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {grouped[status].map((video) => (
              <VideoCard key={video.id} video={video} />
            ))}
          </div>
        </section>
      ))}
    </div>
  );
}
